---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(viridis)
library(ggprism)
```

```{r}
Shrb <- read.csv("../Data/ShrbRNAiPhenotypePenetrance.csv")
```

```{r}
Shrb.summary <- Shrb %>% group_by(Repeat, Genotype) %>% summarize(yes = sum(Phenotype == "Yes"), n = n(), percent = yes/n)
```

```{r}
ggplot(Shrb.summary, aes(x = Genotype, y = percent)) +
  geom_boxplot() +
  geom_point() +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  theme_prism() +
  labs(x = "", y = "")
```

```{r}
p <- ggplot(Shrb.yes, aes(x = Genotype, y = percent, fill = Phenotype)) +
  xlab("Genotype") +
  ylab("Phenotype Penetrance (%)")
p +
  #theme_prism() +
  geom_bar(aes(fill = Genotype), stat = "identity") +
  scale_fill_brewer(palette = "Blues")
```

```{r}
Shrb.summary <- Shrb %>% group_by(Repeat, Genotype, Phenotype) %>% summarise(n = n()) %>% mutate(percent = n/sum(n))
Shrb.yes <- Shrb.summary %>% filter(Phenotype == "Yes") 
```

```{r}
Control <- data.frame(Genotype = "Control", Phenotype = "Yes", n = 1, percent = 0)
Shrb.yes <- rbind(Shrb.yes, Control)
```

```{r}
ggplot(Shrb.yes, aes(x = Genotype, y = percent, fill = Genotype)) +
  geom_boxplot() +
  geom_point() +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  #theme_prism() +
  scale_fill_brewer("Blues") 
  labs(x = "Genotype", y = "Phenotype Penetrance (%)")
  ggsave("../Results/ShrbPhenotype1.pdf")
```

```

